DECLARE @SQL varchar(max)
SELECT @SQL= STUFF((SELECT ';' + 'ALTER TABLE ' + t.TABLE_SCHEMA+'.' +t.TABLE_NAME+ ' ADD isDeleted bit default 0' 
FROM INFORMATION_SCHEMA.TABLES t
WHERE TABLE_TYPE = 'BASE TABLE' and TABLE_SCHEMA='Setup'
      FOR XML PATH('')),1,1,'')
EXEC (@SQL)